:article: 專案產品開發時程之專有名詞 (RFQ,Kick-off,EVT,DVT,PVT,MP)
:title: {article}
:author: Ezra
:mail: admin@meniny.cn
:doctype: book
:page-layout!:
:sectanchors:
:sectlinks:
:sectnums:
:toc: left
:toclevels: 6
:toc-title: 索引
= {title}

== 簡介專案的專有名詞:

* Kickoff – 專案正式開案，時間上不一定在那一個階段
* 選料 – 零件的規格是H/W Engineer在畫線路圖的時候就決定了，料是採購決定
* 備料 – 準備生產時要用的零件材料
* 線路圖 – 標示各個IC和零件之間線路連結狀況的文件
* Layout – 標示各個IC和零件在PCB上面相對位置和線路走線情況的文件
* Co-Lay – 在PCB同一個位子上保留可以放置其他不同規格零件的狀況
* Gerber out – PCB廠用來生產PCB時需要的檔案，通常可以由Layout軟體產生
* PCB out – PCB裸版做好的時候，上面都沒有零件
* 打件 – 把零件放到PCB上面的過程
* SMP件 – IC或是其他元件的針腳是直接接觸PCB平面的，像是BGA封裝的IC
* DIP件 – IC或是其他元件的針腳是穿過PCB的貫孔，像是鋁質電容
* FAI – First Article Inspection 首件檢驗
* Rework – 電路板成品之後需要透過人工的方式修改跳現或是更動元件位置
* EVT – Engineering Validate Time專案流程 工程驗證期
* DVT – Design Validation Test專案流程 開發驗證期
* PreMP (Pre-Production) – 專案流程 小量試量產
* MP (Mess Production) – 專案流程 正式量產產品

== 專案初始時專有名詞

* **RFQ(Request for quotation):** (來源:link:http://www.dotblogs.com.tw/jimmyyu/archive/2010/10/13/kick-off-meeting.aspx[DIGITIMES中文網])

	可被翻譯為詢價或報價單，而RFQ文件內容一般含括貨品描述、數量、交貨日期、交貨處、聯絡人、單價等詳細資訊。

	此外，RFQ也被解讀為1種交易模式，其主要由買方所發動，亦即先由買方詢價，然後再交由賣方報價。以筆記型電腦產業為例，NB品牌廠通常在7~8月間會開始作RFQ詢(報)價動作，確立隔年由哪些代工合作廠接下訂單。

	待詢價期限截止後，相關管理系統便會按Call Number，將詢價的供應商、報價等資訊，通通予以羅列，採購人員即可據此進行比價作業，做出適當的採購決定，接著將RFQ轉化成為採購單(Purchase Order；PO)，向最終出線的供應商發出正式訂單。

* **Kick-off Meeting**:

	顧名思義就是「啟動會議」，通常會發生在專案開始前，型式上的一個會議，以宣告專案的開始，需要在會議前，協調好所有需要的資源，包括相關的人與事、該做的事項、預達目標、重要里程碑等，都一一列好，所有與專案相關的人員都到要到齊，以表示對專案的一種承諾。通常Kick off會議，除了專案成員外，也都會請高階老闆參加，代表著上對下，下對上的彼此承諾，不得馬虎。

== 開發驗證階段專有名詞

工程師出馬了,以上是專案的PM與Sales為主的部份

以下是SW,HW,ME,QA為主角的開發階段

* **EVT: Engineering Validation Test 工程驗證階段** (來源: link:http://www.ptt.cc/bbs/P_Management/M.1211020932.A.CCF.html[kelly7788])

	EVT PR (EVT試產) 為 RD主導，工廠組裝

	使用的 ME housing ，流程上要求為 T1 housing，

	但實際上若 schedule 不允許，也會使用 Mockup Housing.

* * ME = 機構
* * T1 = 塑膠第一次射出的外殼或是第一次的鐵件
* * Mockup 有些公司稱為 prototype
* * Housing = 機構的外殼
* * Mockup Housing = 用快速成型方式做出來外殼，非開模品

組裝之後，這些 sample 會送到各部門做驗證

如 EMI/Safety/Design Qualification Dept….etc 端看各系統的需求

若有通過 EVT exit 的條件才可進入下一個階段

* **DVT: Design Validation Test 設計驗證階段**

	DVT PR (DVT試產) 為 RD 主導，工廠組裝 (但有交接給工廠的意味)

	使用的 Housing 必然為開模品

	Sample 也將送往以上提到的各部門再做驗證

	重頭戲應該是在 Reliability 部門， MTBF 的驗證，以及軟體的測試

* * MTBF = Mean Time between Failure

	看各公司以及系統要求，通常以高溫方式加速老化測試產品壽命

	也有可能不做 MTBF，因為，很~貴~

* Mean time before failure是 MTTF~ (link:http://www.relex.com/resources/mtbf-mttf.asp[http://www.relex.com/resources/mtbf-mttf.asp])

	“Mean time before failure” is a reliability calculation, often referred to as Mean Time To Failure , or MTTF. “Mean time between critical failure” is often simply called Mean Time Between Failures, or MTBF.

* MTTF Versus MTBF

		MTBF (mean time between failures) is the expected time between two successive failures of a system. Therefore, MTBF is a key reliability metric for systems that can be repaired or restored. MTTF (mean time to failure) is the expected time to failure of a system. Non-repairable systems can fail only once. Therefore, for a non-repairable system, MTTF is equivalent to the mean of its failure time distribution. Repairable systems can fail several times. In general, it takes more time for the first failure to occur than it does for subsequent failures to occur. Therefore, MTTF for a repairable system can represent one of two things: (1) the mean time to first failure (MTTFF) or (2) the mean uptime (MUT) within a failure-repair cycle in a long run.

若有通過 DVT exit 的條件才可進入下一階段

(通常是不可以留下任何 B級以上 Bug)

各部門零件承認完畢，軟體承認完畢，硬體承認完畢

客戶承認完畢

* **PVT: Production Validation Test 生產驗證階段**

	PVT PR (PVT試產，也可稱為小量產)

	工廠主導，RD協助

	這個階段的產品應為非常成熟，直逼量產品

	重頭戲在工廠 tune 生產流程以迎接接下來的 MP 大戲

	PVT Sample 仍會留在工廠做 Quality 測試以及 MTBF測試

	通常會邀請客戶在場承認 Golden Sample

	* Golden Sample: 客戶承認邊簽名，最後留在工廠當神像供著做為未來客驗的依據
		* MTBF: 此階段的 MTBF 通常是為了驗證採買的材料品質以及再驗證產品壽命
		* MTBF驗證後的產品通常不可出貨 (因為壽命減短)，但各公司以及客戶要求不同
		* 也有可能不做 MTBF，因為這個驗證是很~貴~的。

* **MP: Mass Production 大量生產**

	工廠大量生產

* **EOL: End Of Life 停產**

	有開始就有結束~

	EOL的三個月前開始發 EOL Notice，通知客戶 EOL 的日期，Last Buy日期，Last Shipment日期，停產日期

	EOL Meeting:
	1. 停產時刻表
	2. 品質 Review以及未來設計改善計畫
	3. 庫存品管理
	4. 備品購買計畫
	5. 後續 Warranty Plan
