title: "Elias's Cave"
name: "Elias's Cave"
url: "https://meniny.cn"
# url: "https://meniny.github.io/Cave"
description: "A Developer's Faux Pas"
introduction: "I am just another boring, tattooed, time traveling developer/designer from China."
copyright: "Elias Abel • 2007-2018"
copyright_full: "Copyright (c) 2007-2018 Elias Abel. All rights reserved"
footnote: "Everything will be ok in the end."

author: "Elias Abel"
author_short: "Elias"
author_avatar: "/assets/image/avatar/default_s.jpg"
other_avatar: "/assets/image/avatar/other_avatar.jpg"
author_description: "Software developer on PC, Linux, Android, iOS and OS X platform. Crafty. Blogger. Traveller. Big fan of Apple. Love of color. Doggies are my fave."

email: "meniny@qq.com"
mail_link: "Mailto:meniny@qq.com?Subject=Hello&nbsp;Elias!"
twitter: "https://twitter.com/_Meniny"
github: "https://github.com/Meniny"
oschina: "https://git.oschina.net/meniny"
appstore: "https://itunes.apple.com/cn/developer/shenyi-li/id1026495349"

default_image: '/assets/images/fire.jpg'
api:
  review: false
  vita: true

future: true

exclude: ['Gemfile.lock', 'Gemfile', 'Rakefile']

highlighter: rouge
#pygments
markdown: kramdown
permalink: /posts/:title/
blog_perma: "https://meniny.cn/posts"
# Plugins
plugins: [jekyll-paginate,jekyll-toc,liquid] #,jekyll-asciidoc]
# Gems
# gems: [jekyll-paginate,jekyll-toc,liquid] #,jekyll-asciidoc]
paginate: 5
paginate_path: "/posts/page/:num"

collections:
  essays:
    output: true
  tweets:
    output: true
  photography:
    output: true
  docs:
    output: true
  posts:
    output: true
  readings:
    output: true
  template:
    output: true

# Default settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
      type: essays
    values:
      layout: "essay"
      category: "Essays"
  - scope:
      path: ""
      type: tweets
    values:
      layout: "tweet"
      category: "Tweets"
  - scope:
      path: ""
      type: photography
    values:
      layout: "album"
      category: "Photography"
  - scope:
      path: ""
      type: docs
    values:
      layout: "doc"
      category: "Documents"
  - scope:
      path: ""
      type: readings
    values:
      layout: "doc"
      category: "Readings"
  - scope:
      path: ""
      type: template
    values:
      layout: "template"
      category: "Template"
  # -
  #   scope:
  #     path: ""
  #     type: pages
  #   values:
  #     layout: "default"
